### PR TITLE
ES6

### PR DESCRIPTION
**Pull request by chriszarate**
- Use Babel to compile to ES5.
- Align with ES6 export syntax (move single export to `generate` method.
- Accept function in `method` option to allow custom hash functions.
- Expose `hashRounds` option to allow overriding default of 10.

### CODE REVIEW

**Comment by chriszarate** [comment]
@denis-sokolov: Interested in your feedback. This introduces a breaking API change by moving away from the single root export (to align with ES6/2015 `export`), so version is bumped to `3.0.0`. Given that, we have a the opportunity to make other breaking changes if they would be beneficial.

**Comment by denis-sokolov** [comment]
There is a slight issue that this PR is clearly a result of unstructured experimentation. Whereas one could expect five separate PRs that can be discussed individually (convert to es2015, add eslint, add `hashRounds`, add `method` functions, refactor tests), we have one giant commit instead. This makes review exponentially harder, because to understand the changes, I need to understand it all at once. It also raises risk of errors being introduced in the changes, as well as highly damages the utility of `git bisect`.

The addition of a build step is a burden on contributors (not that we had a lot of contributions before). In general, a build step is an annoyance and a complexity cost, it better bring considerable benefits. And I don’t see any particular benefits here.

The addition of `method` taking a function is not bad, but from usability point of view, I’d rather we provide a good option for the user ourselves instead of shifting the responsibility on the user. Who wants to worry about their hashing function?

The switch from Node 0.10 to Node 6 in Travis is a bit confusing. Do we only support Node 6 now? If yes, we should note it in `package.json` using `engines` field. If no, we should test on many Node versions to ensure it keeps working on older versions.

I am not meaning to be negative. I am happy you’re putting good work into the project. The new set of tools is modern and good (ava, eslint, babel over gulp, jshint, nodeunit). But my job is to provide constructive criticism to continue moving forward. :)

**Comment by chriszarate** [comment]
Thanks for the feedback, much appreciated!

1. You're right that this is the result of "unstructured experimentation"—in large part to help familiarize myself with ES2015. I'd be happy to go back and modularize the commits, but moving to a new syntax means this can only go so far.

2. The build step is completely optional, even for contributors. Tests run against ES2015 code in `src` and one never need run `npm run compile`. It will be run automatically when published to npm and contributors won't need to create or look at `dist`. Perhaps I'm missing your point here, though.

3. The `method` parameter still accepts a string (e.g., `md5` or `sha512`) corresponding to built-in hash functions, so it doesn't shift the burden to the user. Rather it will now also accept a function (it does a type check). I'm not crazy about `method` accepting both `String` and `Function`, so curious if you might propose another way.

4. I was troubleshooting a problem with `ava` and `babel-plugin-__coverage__` and changed the Travis-CI config to Node 6 without meaning to make it permanent. I'll add several earlier versions as I don't think we need to drop support unnecessarily.

**Comment by denis-sokolov** [comment]
As you said, modularizing the changes after the fact is trickier, especially with the new syntax. I’d suggest not to bother this time.

If the build step is for publishing only, that’s great. I did not see it the first time.

I understand that method takes `md5` and `sha512` as well as functions (which, by the way, is completely fine). I am questioning the purpose of allowing a custom function. Is it to enable better hash functions? Why not add a better hash function ourselves, then? Same with `hashRounds`. Why would anyone need to customize that?

**Comment by chriszarate** [comment]
Yes, the idea is to allow implementers to use their preferred hash function without needing this package to add it. We may not want to add it, or it may not be available in a nice modular package like `crypto-js`. Further, every hash function we add increases the size of the library, which is a factor for anyone using tools like `browserify` and `webpack` (as `supergenpass` does).

A `hashRounds` options is often requested as a way to make brute-forcing the master password more computationally expensive (At about 10,000 rounds, generation times start approaching half a second). That's a fairly compelling reason to me, if not a mainstream use case.

**Comment by denis-sokolov** [comment]
You have convinced me!

**Pull request merged**
